// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeGDEvGhxrQpVzKk3qB5_Jl5PCSdEXkxg',
    appId: '1:645368066947:web:b2e51fa7a707d30a0c3cb6',
    messagingSenderId: '645368066947',
    projectId: 'flutter-spotify-clone-fldx',
    authDomain: 'flutter-spotify-clone-fldx.firebaseapp.com',
    storageBucket: 'flutter-spotify-clone-fldx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbH9N3u9OiR16NZU-Qc9cO7nT2V8cDb-I',
    appId: '1:645368066947:android:7ab379969a9fd4550c3cb6',
    messagingSenderId: '645368066947',
    projectId: 'flutter-spotify-clone-fldx',
    storageBucket: 'flutter-spotify-clone-fldx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDubd5jffU5fswW7L_pjF3sC_dTgq4SJVI',
    appId: '1:645368066947:ios:f4dae74b4238b03f0c3cb6',
    messagingSenderId: '645368066947',
    projectId: 'flutter-spotify-clone-fldx',
    storageBucket: 'flutter-spotify-clone-fldx.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDubd5jffU5fswW7L_pjF3sC_dTgq4SJVI',
    appId: '1:645368066947:ios:f4dae74b4238b03f0c3cb6',
    messagingSenderId: '645368066947',
    projectId: 'flutter-spotify-clone-fldx',
    storageBucket: 'flutter-spotify-clone-fldx.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeGDEvGhxrQpVzKk3qB5_Jl5PCSdEXkxg',
    appId: '1:645368066947:web:428bd539034564120c3cb6',
    messagingSenderId: '645368066947',
    projectId: 'flutter-spotify-clone-fldx',
    authDomain: 'flutter-spotify-clone-fldx.firebaseapp.com',
    storageBucket: 'flutter-spotify-clone-fldx.firebasestorage.app',
  );
}
